"""
Production Hive Models - Data structures for content generation

These models represent the production artifacts and agent outputs
as defined in the mathematical specification.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Optional
from pathlib import Path
from pydantic import BaseModel, Field


class ContentType(str, Enum):
    """Types of content that can be generated."""
    VIDEO = "video"
    IMAGE = "image"
    AUDIO = "audio"
    TEXT = "text"


class AgentRole(str, Enum):
    """Roles of agents in the production hive."""
    VISUALIST = "visualist"  # Agent A - Image generation
    CRITIC = "critic"        # Agent B - Quality assessment
    EDITOR = "editor"        # Agent C - Video assembly
    AUDIO = "audio"          # Agent D - Music/audio generation


class AgentResult(BaseModel):
    """Result from a single agent's work."""
    
    agent_role: AgentRole
    success: bool = True
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    
    # Output paths
    output_path: Optional[Path] = None
    output_paths: list[Path] = Field(default_factory=list)
    
    # Quality metrics
    quality_score: float = Field(default=0.0, ge=0.0, le=1.0)
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    
    # Metadata
    iterations: int = Field(default=1)
    processing_time_ms: int = Field(default=0)
    metadata: dict = Field(default_factory=dict)
    
    # Error handling
    error_message: Optional[str] = None
    
    class Config:
        arbitrary_types_allowed = True


class ImageVariation(BaseModel):
    """A single image variation generated by the Visualist."""
    
    id: str
    path: Path
    prompt_used: str
    style_tags: list[str] = Field(default_factory=list)
    
    # CLIP similarity scores
    brand_alignment_score: float = Field(default=0.0, ge=0.0, le=1.0)
    prompt_adherence_score: float = Field(default=0.0, ge=0.0, le=1.0)
    
    # Selection metadata
    selected: bool = False
    critic_notes: Optional[str] = None
    
    class Config:
        arbitrary_types_allowed = True


class AudioTrack(BaseModel):
    """Generated audio track."""
    
    id: str
    path: Path
    duration_seconds: float
    
    # Audio parameters (θ_music)
    tempo: float
    key: str
    mood: str
    energy: float = Field(ge=0.0, le=1.0)
    
    # Quality metrics
    quality_score: float = Field(default=0.0, ge=0.0, le=1.0)
    
    class Config:
        arbitrary_types_allowed = True


class TextOverlay(BaseModel):
    """Text overlay configuration for video."""
    
    id: str
    text: str
    position: tuple[float, float] = (0.5, 0.8)  # Relative position
    font_size: int = 24
    font_family: str = "Arial"
    color: str = "#FFFFFF"
    background_color: Optional[str] = "rgba(0,0,0,0.5)"
    animation: str = "fade_in"  # fade_in, slide_up, typewriter
    start_time: float = 0.0
    duration: float = 3.0


class GeneratedContent(BaseModel):
    """
    Complete generated content package.
    
    Represents v_t = H(G_V(b_t, θ_music; z), G_T(b_t, θ_text), a_t^text)
    """
    
    id: str = Field(..., description="Unique content identifier")
    brief_id: str = Field(..., description="Source creative brief ID")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    
    # Content paths
    video_path: Optional[Path] = None
    thumbnail_path: Optional[Path] = None
    
    # Components
    images: list[ImageVariation] = Field(default_factory=list)
    audio: Optional[AudioTrack] = None
    text_overlays: list[TextOverlay] = Field(default_factory=list)
    
    # Agent results
    agent_results: dict[str, AgentResult] = Field(default_factory=dict)
    
    # Quality metrics
    overall_quality_score: float = Field(default=0.0, ge=0.0, le=1.0)
    brand_alignment_score: float = Field(
        default=0.0, 
        ge=0.0, 
        le=1.0,
        description="CLIPSim(v_t, θ_brand_aesthetic)"
    )
    
    # Production metadata
    total_processing_time_ms: int = Field(default=0)
    production_cost: float = Field(default=0.0)
    
    # Deployment info
    deployed: bool = False
    platform_ids: dict[str, str] = Field(default_factory=dict)
    
    class Config:
        arbitrary_types_allowed = True


class HiveReward(BaseModel):
    """
    Hive reward proxy (pre-engagement).
    
    r_t^hive = E[CLIPSim(v_t, θ_brand_aesthetic)] - λ||δ^music||_1 - μ||δ^text||_1
    """
    
    content_id: str
    
    # Reward components
    clip_similarity: float = Field(ge=0.0, le=1.0)
    music_perturbation_penalty: float = Field(ge=0.0)
    text_perturbation_penalty: float = Field(ge=0.0)
    
    # Hyperparameters
    lambda_music: float = Field(default=0.1)
    mu_text: float = Field(default=0.1)
    
    @property
    def total_reward(self) -> float:
        """Calculate total hive reward."""
        return (
            self.clip_similarity 
            - self.lambda_music * self.music_perturbation_penalty
            - self.mu_text * self.text_perturbation_penalty
        )
